### ISSUE TITLE
Split cleanfit into two separate methods

### ISSUE THREAD

**Issue by codepictor** [cetic/tsquared#5]
Hi there!

First of all, thank you for developing this great package! It really helps understand how Hotelling's T2 works and how this algorithm can be applied to analyzing multivariate time series data.

Let's take a look at the following code snippet:

```
import numpy as np
import tsquared

X = np.array([[-1.0], [1.0], [-1.0], [1.0]])

clf = tsquared.HotellingT2(alpha=0.5)
clf.cleanfit(X, iter=1)
```

This code raises an exception:

`ValueError: Found array with 0 sample(s) (shape=(0, 1)) while a minimum of 1 is required by HotellingT2.`

I think it is worth considering to split the method _cleanfit_ into two separate methods: _clean_ and _fit_. So, a user can call the _clean_ method, which returns a clean dataset. If this clean dataset contains too few samples, a user can decide what to do next (and the exception will be raised only if this clean dataset will be passed to the _fit_ method). For example, a raw dataset can be passed to the _fit_ method instead of a clean one.

 Also, a method _clean_fit_ can be added to the package (like _fit_transform_ in sklearn).

Would be glad to hear any feedback from you. Thanks!

**Comment by Nico-Salamone** [comment]
Hi!

Thanks for your interest in the project and for your great suggestion!

You're right: `cleanfit` method was a bad smell and the clean part should have been in a separate function. That's why I've just created a new file, `utils.py`, containing a set of tools around Hotelling's T-squared test. For the moment, only one function is defined: `clean_samples`.

The `clean_samples` function is the equivalent to the old `cleanfit` method but without the fit part. Note that I've completely refactored the code and the parameters and that I've updated the docstring. An example can be found in [`tsquared/examples/clean_samples/clean_samples.py`](https://github.com/cetic/tsquared/blob/6b68648412047bc9a286e62ccf93f10fcfca71b2/examples/clean_samples/clean_samples.py).

The code equivalent to your code snippet is as followings:

```python
import numpy as np
import tsquared

X = np.array([[-1.0], [1.0], [-1.0], [1.0]])
alpha=0.5

X_clean = tsquared.clean_samples(X, n_iters=1, perc_samples=0, hz_test=False, alpha=alpha)
clf = tsquared.HotellingT2(alpha=alpha)
clf.fit(X_clean)
```

Once again, thanks for your contribution!
